# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - |-
        mkdir -p dist
        GOOS=windows go build -o dist .
        GOOS=linux go build -o dist .


  run-cn:
    - ./dist/llxh -j 64 -u https://ossweb-img.qq.com/upload/adw/image/752/20211219/f4b5919ec683f49d8532cef90644b9ac.jpeg 10240
